# Exporting

export ZSHPLUG=$HOME/shells/zsh
export TERM=xterm-256color
export _JAVA_AWT_WM_NONREPARENTING=1

# If not running interactively, don't do anything
[[ $- != *i* ]] && return

# History {{{
HISTFILE=~/.histfile
HISTSIZE=1000
SAVEHIST=1000
HISTDUP=erase
setopt HIST_EXPIRE_DUPS_FIRST
setopt HIST_IGNORE_DUPS
setopt HIST_IGNORE_ALL_DUPS
setopt HIST_IGNORE_SPACE
setopt HIST_FIND_NO_DUPS
setopt HIST_SAVE_NO_DUPS
# }}}

# ZSH AUTOGENERATED {{{
bindkey -e
# The following lines were added by compinstall
zstyle :compinstall filename '/home/eveloth/.zshrc'

autoload -Uz compinit
compinit
# End of lines added by compinstall
# }}}

# Aliases {{{
alias dir='dir --color=auto'
alias egrep='egrep --color=auto'
alias fgrep='fgrep --color=auto'
alias fixpacman="sudo rm /var/lib/pacman/db.lck"
alias grep='grep --color=auto'
alias grubup="sudo update-grub"
alias hw='hwinfo --short'
alias psmem10='ps auxf | sort -nr -k 4 | head -10'
alias psmem='ps auxf | sort -nr -k 4'
alias rmpkg="sudo pacman -Rdd"
alias tarnow='tar -acf '
alias untar='tar -zxvf '
alias upd='/usr/bin/update'
alias vdir='vdir --color=auto'
alias wget='wget -c '

alias cp='cp -v'
alias mv='mv -v'

# ls to exa

alias ls='exa -al --color=always --group-directories-first --icons' # preferred listing
alias la='exa -a --color=always --group-directories-first --icons'  # all files and dirs
alias ll='exa -l --color=always --group-directories-first --icons'  # long format
alias lt='exa -aT --color=always --group-directories-first --icons' # tree listing
alias l.="exa -a | egrep '^\.'"                                     # show only dotfiles
alias ip="ip -color"

# Git

alias push='git push origin'
alias pull='git pull origin'

# Changing directories

alias ..='cd ..'

# FaxOS

alias cl='clear'
alias sun='shutdown now'
alias vim='nvim'

# }}}

# Plugins {{{

source $ZSHPLUG/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
source $ZSHPLUG/zsh-autosuggestions/zsh-autosuggestions.zsh

# }}}

# INIT

neofetch
eval "$(starship init zsh)"
