exec-once = dbus-launch gentoo-pipewire-launcher
exec-once = ~/.config/hypr/portalstart
exec-once = /usr/libexec/polkit-gnome-authentication-agent-1
exec-once = eww daemon
exec-once = eww open bar
exec-once = swww init
exec-once = swww img /home/eveloth/doc/zettelkasten/Base/Wallpapers/starry_night.jpeg

exec-once = hyprctl setcursor Bibata-Modern-Ice 24
